### ISSUE TITLE
Bug "A component is changing an uncontrolled input of type text to be controlled"

### ISSUE THREAD

**Issue by Daniil-Kudlach** [AleksandrKoltsov/camp_site#27]
![error_conroledComponent](https://user-images.githubusercontent.com/54568862/83348298-dd51b300-a333-11ea-904c-30036b7743c6.png)

**Comment by AleksandrKoltsov** [comment]
fixed bug => when create state: no type 
![image](https://user-images.githubusercontent.com/41367097/84046274-89d60980-a9b2-11ea-9bf8-267bb1f59590.png)
The solution is to add the state type when declaring
