### ISSUE TITLE
Height for cardSlider components (need to add more?)

### ISSUE THREAD

**Issue by Daniil-Kudlach** [AleksandrKoltsov/camp_site#36]
![Screenshot_2020-06-02_19-17-49](https://user-images.githubusercontent.com/54568862/83543936-d5e20380-a505-11ea-8876-4fba662839dc.png)

**Comment by AleksandrKoltsov** [comment]
add 20% height and padding text 1rem

**Comment by Daniil-Kudlach** [comment]
![Screenshot_2020-06-02_19-46-01](https://user-images.githubusercontent.com/54568862/83546744-d381a880-a509-11ea-9f44-29145dfa4c52.png)
