### ISSUE TITLE
Invalid stars render at feedback messages (in form 10 - in message 9)

### ISSUE THREAD

**Issue by Daniil-Kudlach** [AleksandrKoltsov/camp_site#37]
![Screenshot_2020-06-02_19-26-19](https://user-images.githubusercontent.com/54568862/83544815-286fef80-a507-11ea-98c9-09be7283710c.png)

**Comment by AleksandrKoltsov** [comment]
fix bug 
![image](https://user-images.githubusercontent.com/41367097/83549274-ba7af680-a50d-11ea-8a03-979581d7f800.png)
