### ISSUE TITLE
Create Message component and add to Form&&Feedback POST 

### ISSUE THREAD

**Issue by Daniil-Kudlach** [AleksandrKoltsov/camp_site#45]
-***Component get message props (string).***
-***100vh height, 100vw width.***
-***show message about POST request in the centre of the screen.***
-***Render as content in App (`setState({...state, content<Message/>})`) when POST method get requests result***
-***Change Loader render in App - add Loader with Component (Form or FeedbackForm) for example (`{this.state.formLoad&&<Loader open={true}/>}<Form/>`)***
-***Be happy***

**Comment by AleksandrKoltsov** [comment]
patch complete
