### ISSUE TITLE
FullCard xs size bug

### ISSUE THREAD

**Issue by Daniil-Kudlach** [AleksandrKoltsov/camp_site#63]
![BUG_2020-06-07_21-53-21](https://user-images.githubusercontent.com/54568862/83977508-96eaee00-a909-11ea-9c5b-83686c1ed688.png)

**Comment by AleksandrKoltsov** [comment]
fixed gug 
![image](https://user-images.githubusercontent.com/41367097/84005412-c6374480-a975-11ea-99c6-d256607c6e28.png)
there was a problem in local style (root : 100vh changed on 100%)
