### ISSUE TITLE
Make social logo in footer smaller

### ISSUE THREAD

**Issue by Daniil-Kudlach** [AleksandrKoltsov/camp_site#70]
![TODO_2020-06-08_17-50-52](https://user-images.githubusercontent.com/54568862/84045008-f6500900-a9b0-11ea-89e0-b1e1661fd5d4.png)

**Comment by AleksandrKoltsov** [comment]
![image](https://user-images.githubusercontent.com/41367097/84058802-6a46dd00-a9c2-11ea-8561-f97ef65afe3a.png) so fit???

**Comment by AleksandrKoltsov** [comment]
ok, leave as is

**Comment by AleksandrKoltsov** [comment]
completed
